config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/search/gyms" => "pages#search", as: :home_search

  get "/signup" => "signup#new"
  post "/signup" => "signup#create"

  get "/confirmation" => "confirmation#show"

  get "/login" => "login#new"
  post "/login" => "login#create"
  delete "/logout" => "login#destroy"

  resources :gyms, only: [:new, :create, :index, :destroy, :show]
  patch "/gym/:id/approve" => "gyms#approve", as: :approve_gym

  post "/daily_token" => "daily_token#create"
  get "/daily_tokens" => "daily_token#index"
  patch "/daily_token/:id/validate" => "daily_token#validate", as: :validate_token
end

app/models/daily_token.rb
class DailyToken < ApplicationRecord
  belongs_to :user
  belongs_to :gym

  before_create do |daily_token|
    daily_token.token = SecureRandom.urlsafe_base64
    daily_token.expires_at =  Time.current.end_of_day
  end

  def validate!
    return if validated? or expired?
    Time.use_zone("America/Sao_Paulo") do
      self.validate_at = Time.current
    end
    self.token = ""
    save!
  end

  def validated?
    validate_at.present?
  end

  def expired?
    Time.use_zone("America/Sao_Paulo") do
      Time.current >= self.expires_at
    end
  end
end

app/controllers/daily_token_controller.rb
class DailyTokenController < ApplicationController

  def create
    gym = Gym.find(params[:gym_id])
    unless current_user.daily_tokens.empty?
       if user_has_retrieved_today_token?
         redirect_to gym_path(gym), alert: "Você já solicitou o seu token diário hoje."
         return
       end
    end
    @daily_token = current_user.daily_tokens.build(gym: gym)
    if @daily_token.save
      redirect_to gym_path(gym), notice: "Solicitação realizada com sucesso. Aguardando aprovação"
    else
      redirect_to gym_path(gym), alert: "Não foi possível completar a sua solicitação. Por favor contate o suporte."
    end
  end

  def index
    if current_user.gympass_employee?
      @daily_tokens = DailyToken.joins(:gym).where("gyms.id = ?", params[:gym_id])
    else
      @daily_tokens = current_user.gyms.find(params[:gym_id]).daily_tokens
    end
  end

  def validate
    if current_user.gympass_employee?
      @daily_token = DailyToken.find(params[:id])
    else
      @daily_token = DailyToken.joins(gym: :users).where("users.id = ? and daily_tokens.id = ?", current_user.id, params[:id]).first
    end
    if @daily_token
      if @daily_token.validate!
        redirect_to daily_tokens_path(gym_id: @daily_token.gym.id), notice: "Token Diário aprovado com sucesso."
      else
        redirect_to daily_tokens_path(gym_id: @daily_token.gym.id), alert: "Não foi possível completar a sua solicitação. Contate o suporte."
      end
    end
  end

  private

  def user_has_retrieved_today_token?
    current_user.daily_tokens.any? { |t| t.created_at.between?(Time.current.beginning_of_day, Time.current.end_of_day) }
  end
end

app/views/daily_token/index.html.erb
<div class="row">
  <div class="col-md-12">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Academia</th>
          <th>Solicitante</th>
          <th>Data da solicitação</th>
          <th>Data da expiração</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @daily_tokens.each do |daily_token| %>
        <tr>
          <td><%= daily_token.gym.name %></td>
          <td><%= daily_token.user.email %></td>
          <td><%= daily_token.created_at.to_s(:gympass) %></td>
          <td><%= daily_token.expires_at.to_s(:gympass) %></td>
          <td><%= daily_token.validated? ? "Aprovado em: #{daily_token.validate_at.to_s(:gympass)}"  : "Pendente" %></td>
          <td>
            <%= button_to "Aprovar", validate_token_path(daily_token), method: :patch,
            data: { confirm: "Deseja realmente aprovar este token" },
            class: "btn btn-warning", disabled: daily_token.validated? or daily_token.expired?  %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>