config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/search/gyms" => "pages#search", as: :home_search

  get "/signup" => "signup#new"
  post "/signup" => "signup#create"

  get "/confirmation" => "confirmation#show"

  get "/login" => "login#new"
  post "/login" => "login#create"
  delete "/logout" => "login#destroy"

  resources :gyms, only: [:new, :create, :index, :destroy, :show]
  patch "/gym/:id/approve" => "gyms#approve", as: :approve_gym

  post "/daily_token" => "daily_token#create"
  get "/daily_tokens" => "daily_token#index"
  patch "/daily_token/:id/validate" => "daily_token#validate", as: :validate_token
end

app/views/pages/home.html.erb
<% if current_user.nil? or current_user.gym_manager? %>
  <div class="row">
    <div class="col-md-12">
      <h2> Seja bem vindo ao Gympass Toy App!
    </div>
  </div>
<% end %>

<% if logged_in? %>
  <% if current_user.regular_end_user? or current_user.gympass_employee? %>
  <div class="row">
    <div class="col-md-12">
      <h2> Encontre uma academia próxima de você!
    </div>
  </div>
    <%= form_tag(home_search_path, method: :get) do %>
      <div class="row">
        <div class="col-md-3">
          <%= label_tag do %>
            <%= radio_button_tag "type_of_location", "current", true %>
            Próximo a minha localização atual
          <% end %>
        </div>
        <div class="col-md-2">
          <%= label_tag do %>
            <%= radio_button_tag "type_of_location", "home" %>
            Próximo a minha casa
          <% end %>
        </div>
        <div class="col-md-3">
          <%= label_tag do %>
            <%= radio_button_tag "type_of_location", "work" %>
            Próximo ao meu trabalho
          <% end %>
        </div>
        <div class="col-md-2">
          <%= label_tag do %>
            <%= radio_button_tag "type_of_location", "arbitrary" %>
            Localização arbritária
          <% end %>
        </div>
        <div class="col-md-2">
          <%= submit_tag "Buscar", class: "btn-search btn btn-primary" %>
        </div>
      </div>
      <div id="search-arbitrary-section" class="row" style="display: none;">
        <div class="col-md-4">
          <%= label_tag do %>
            Latitude
            <%= number_field_tag "latitude", nil, step: "any" %>
          <% end %>
        </div>
        <div class="col-md-4">
          <%= label_tag do %>
            Logintude
            <%= number_field_tag "longitude", nil, step: "any" %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="row" style="margin-top: 5%; font-size: 2em;">
      <div class="col-md-12">
        <ul>
          <% unless @gyms.nil? %>
            <% @gyms.each do |gym| %>
            <li><%= link_to gym.name, gym %></li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>
<script type="text/javascript">
  $(":radio[name='type_of_location']").on("change", function(){
    if ("type_of_location_arbitrary" == this.id) {
      $("#search-arbitrary-section").show();
    } else {
      $("#latitude").val("");
      $("#longitude").val("");
      $("#search-arbitrary-section").hide();
    }
  });
</script>