config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/search/gyms" => "pages#search", as: :home_search

  get "/signup" => "signup#new"
  post "/signup" => "signup#create"

  get "/confirmation" => "confirmation#show"

  get "/login" => "login#new"
  post "/login" => "login#create"
  delete "/logout" => "login#destroy"

  resources :gyms, only: [:new, :create, :index, :destroy, :show]
  patch "/gym/:id/approve" => "gyms#approve", as: :approve_gym

  post "/daily_token" => "daily_token#create"
  get "/daily_tokens" => "daily_token#index"
  patch "/daily_token/:id/validate" => "daily_token#validate", as: :validate_token
end

app/models/gym.rb
class Gym < ApplicationRecord
  has_one :location, dependent: :destroy, as: :localizable
  has_many :gym_users, dependent: :destroy
  has_many :users, through: :gym_users
  has_many :daily_tokens

  acts_as_mappable through: :location

  enum status: [:pending, :approved]

  before_create do |gym|
    gym.cnpj.remove!(/\D/)
  end

  def opening_hourary
    hourary(opening_time_in_sec.to_f).to_s(:time)
  end

  def closing_hourary
    hourary(closing_time_in_sec.to_f).to_s(:time)
  end

  def closed?
    Time.use_zone("America/Sao_Paulo") do
      Time.current >= hourary(self.closing_time_in_sec.to_f)
    end
  end

  private

  def hourary(sec)
    Time.current.beginning_of_day + sec
  end
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController

  def new
    @gym_registration = GymRegistration.new
  end

  def create
    @gym_registration = GymRegistration.new(gym_registration_params)
    if @gym_registration.valid?
      Gym.transaction do
        gym = @gym_registration.save(current_user)
        if gym.persisted?
          redirect_to root_path, notice: "Academia cadastrada com sucesso. Aguardando aprovação!"
        end
      end
    else
      render :new
    end
  end

  def show
    @gym = Gym.approved.find(params[:id])
  end

  def index
    if current_user.gympass_employee?
      @gyms = Gym.all
    else
      @gyms = current_user.gyms
    end
  end

  def approve
    unless current_user.gympass_employee?
      redirect_to gyms_path, error: "Ação não permitida!"
      return
    end
    @gym = Gym.find(params[:id])
    if @gym
      Gym.transaction do
        @gym.approved!
        GymApprovalMailer.approval_email(@gym).deliver_now
        redirect_to gyms_path, notice: "#{@gym.name} foi aprovada com sucesso!"
      end
    else
      redirect_to gyms_path, error: "Academia não encontrada!"
    end
  end

  def destroy
    redirect_to gyms_path, error: "Ação não permitida!" unless current_user.gympass_employee? or current_user.gym_manager?
    if current_user.gym_manager?
      @gym = current_user.gyms.find(params[:id])
    elsif current_user.gympass_employee?
      @gym = Gym.find(params[:id])
    end
    if @gym
      @gym.destroy!
      redirect_to gyms_path, notice: "#{@gym.name} foi removida com sucesso!"
    else
      redirect_to gyms_path, error: "Academia não encontrada!"
    end
  end

  def gym_registration_params
    params.require(:gym_registration)
      .permit(:name, :cnpj, :location_latitude, :location_longitude, :opening_time_hour, :opening_time_min, :closing_time_hour, :closing_time_min, :gym_managers => [])
  end
end

app/views/gyms/index.html.erb
<div class="row">
  <div class="col-md-12 col-md-offset-10">
    <%= link_to("Registrar academia", new_gym_path, class: "btn btn-primary", html_options: {role: "button" }) %>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>Nome Fantasia</th>
          <th>CNPJ</th>
          <th>Horário de abertura</th>
          <th>Horário de fechamento</th>
          <th>Daily Tokens</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @gyms.each do |gym| %>
        <tr>
          <td><%= gym.name %></td>
          <td><%= gym.cnpj %></td>
          <td><%= gym.opening_hourary %></td>
          <td><%= gym.closing_hourary %></td>
          <td>
            <%= link_to("#{gym.daily_tokens.count}", daily_tokens_path(gym_id: gym.id), class: "btn btn-primary", html_options: {role: "button" }) %>
          </td>
          <td><%= gym.status %></td>
          <% if current_user.gympass_employee? %>
          <td>
            <%= button_to "Aprovar", approve_gym_path(gym), method: :patch,
            data: { confirm: "Deseja realmente aprovar a academia #{gym.name}?" },
            class: "btn btn-warning", disabled: gym.approved? %>
          </td>
          <% end %>
          <td>
            <%= button_to "Deletar", gym, method: :delete,
            data: { confirm: "Deseja realmente remover a #{gym.name}?" },
            class: "btn btn-danger" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/gyms/new.html.erb
<%= simple_form_for(@gym_registration, url: gyms_path) do |f| %>
  <div class="row">
    <div class="col-md-4">
      <%= f.input :name, label: "Nome Fantasia", required: true,  input_html: { maxlength: 100 } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= f.input :cnpj, label: "CNPJ", required: true,  input_html: { maxlength: 18 } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= f.input :opening_time_hour, label: "Hora de abertura", as: :integer, input_html: { max: 23, min: 0 }, required: true %>
    </div>
    <div class="col-md-2">
      <%= f.input :opening_time_min, label: "Minuto de abertura", as: :integer, input_html: { max: 59, min: 0 }, required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= f.input :closing_time_hour, label: "Hora de fechamento", as: :integer, input_html: { max: 23, min: 0 }, required: true %>
    </div>
    <div class="col-md-2">
      <%= f.input :closing_time_min, label: "Minuto de fechamento", as: :integer, input_html: { max: 59, min: 0 }, required: true %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= f.input :location_latitude, as: :float, label: "Endereço latitude" %>
    </div>
    <div class="col-md-2">
      <%= f.input :location_longitude, as: :float, label: "Endereço longitude" %>
    </div>
  </div>
  <div class="row">
    <%= label_tag "Outros administradores:" %>
    <div class="col-md-12">
      <%= f.collection_check_boxes :gym_managers, gym_managers_coll(current_user.email), :first, :last, item_wrapper_class: "checkbox-inline" %>
    </div>
  </div>
  <div class="row" style="margin-top: 5%;">
    <div class="col-md-2">
      <%= f.button :submit, "Cadastrar" %>
    </div>
  </div>
<% end %>

app/views/gyms/show.html.erb
<p>
  <strong>Nome Fantasia:</strong>
  <%= @gym.name %>
</p>

<p>
  <strong>CNPJ:</strong>
  <%= @gym.cnpj %>
</p>

<p>
  <strong>Horário de abertura:</strong>
  <%= @gym.opening_hourary %>
</p>
<p>
  <strong>Horário de fechamento:</strong>
  <%= @gym.closing_hourary %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @gym.location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @gym.location.longitude %>
</p>
<div class="row">
  <div class="col-md-2">
    <%= link_to "Voltar", root_path %>
  </div>
  <div class="col-md-2">
    <%= button_to "Solicitar Token", daily_token_path(gym_id: @gym.id), method: :post,
    data: { confirm: "Deseja realmente solicitar seu token diário para a academia #{@gym.name}?" },
    class: "btn btn-warning", disabled: @gym.closed? %>
  </div>
</div>