config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/search/gyms" => "pages#search", as: :home_search

  get "/signup" => "signup#new"
  post "/signup" => "signup#create"

  get "/confirmation" => "confirmation#show"

  get "/login" => "login#new"
  post "/login" => "login#create"
  delete "/logout" => "login#destroy"

  resources :gyms, only: [:new, :create, :index, :destroy, :show]
  patch "/gym/:id/approve" => "gyms#approve", as: :approve_gym

  post "/daily_token" => "daily_token#create"
  get "/daily_tokens" => "daily_token#index"
  patch "/daily_token/:id/validate" => "daily_token#validate", as: :validate_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Authentication
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gym_managers_coll(exclude = nil)
     User.gym_manager.merge(User.confirmed)
    .where.not(email: exclude)
    .order(:email).inject([]) { |coll, gm| coll << [gm.id, gm.email] }
  end
end

app/views/application/_flash_messages.html.erb
<% FlashMessages.call(flash).each do |type, message| %>
  <p class="alert alert-<%= FlashMessages.css_class(type.to_sym) %>" role="alert"><%= message %></p>
<% end %>

app/views/application/_main_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Gympass Toy App", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
          <% if current_user.gym_manager? or current_user.gympass_employee?  %>
            <li><%= link_to "Academias", gyms_path %></li>
          <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="current-user-name">
            <p class="navbar-text">
              Logado como <%= current_user.name %> - <%= current_user.role.titleize %>
            </p>
          </li>
          <li><%= button_to "Sair", logout_path, method: "delete", class: "btn btn-default navbar-btn" %></li>
        <% else %>
          <li><%= link_to "Cadastro", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>